/*
  Read-only lookup for a handheld scan.
  Supply @scanValue as a parameter from the API; never concatenate it into SQL.
  GOODS_CODE supports a packaging/unit-specific code; SKU_BARCODE is a SKU-level fallback.
*/
SELECT
  GOODSMASTER.GOODS_KEY,
  GOODSMASTER.GOODS_CODE,
  SKUMASTER.SKU_KEY,
  SKUMASTER.SKU_CODE,
  SKUMASTER.SKU_NAME,
  SKUMASTER.SKU_BARCODE,
  UOFQTY.UTQ_KEY AS UNIT_KEY,
  UOFQTY.UTQ_NAME AS SCANNED_UNIT_CODE,
  UOFQTY.UTQ_QTY AS UNIT_MULTIPLIER
FROM GOODSMASTER
INNER JOIN SKUMASTER ON GOODSMASTER.GOODS_SKU = SKUMASTER.SKU_KEY
INNER JOIN UOFQTY ON GOODSMASTER.GOODS_UTQ = UOFQTY.UTQ_KEY
WHERE LTRIM(RTRIM(GOODSMASTER.GOODS_CODE)) = @scanValue
   OR LTRIM(RTRIM(SKUMASTER.SKU_BARCODE)) = @scanValue;
