/*
  Receipts: first source query confirmed by the business team.
  Filter by SKU_KEY so every packaging barcode for the same SKU shares one history.
*/
SELECT TOP (@historyLimit)
  DOCINFO.DI_REF,
  DOCINFO.DI_DATE,
  CAST(LEFT(TRD_SH_REMARK, 255) AS VARCHAR(255)) AS TRD_SH_REMARK,
  TRANSTKD.TRD_SH_QTY,
  TRANSTKD.TRD_EXP_D,
  WARELOCATION.WL_CODE,
  TRANSTKD.TRD_UTQNAME,
  WL.WLCODE AS TRD_TO_WL,
  SKUMASTER.SKU_KEY,
  GOODSMASTER.GOODS_KEY
FROM DOCINFO,
  DOCTYPE,
  TRANSTKD,
  BRANCH,
  GOODSMASTER,
  SKUMASTER,
  WARELOCATION,
  WAREHOUSE,
  (SELECT WL_KEY AS WLKEY, WL_CODE AS WLCODE FROM WARELOCATION) AS WL,
  TRANSTKH
  LEFT OUTER JOIN APPRICETAB ON TRANSTKH.TRH_ARPRB = APPRICETAB.APPRB_CODE
WHERE
  DOCINFO.DI_DT = DOCTYPE.DT_KEY
  AND DOCINFO.DI_ACTIVE = 0
  AND DOCTYPE.DT_PROPERTIES IN (311, 312)
  AND DOCINFO.DI_KEY = TRANSTKH.TRH_DI
  AND TRANSTKH.TRH_KEY = TRANSTKD.TRD_TRH
  AND TRANSTKH.TRH_BR = BRANCH.BR_KEY
  AND TRANSTKD.TRD_SKU = SKUMASTER.SKU_KEY
  AND TRANSTKD.TRD_GOODS = GOODSMASTER.GOODS_KEY
  AND TRANSTKD.TRD_WL = WARELOCATION.WL_KEY
  AND WARELOCATION.WL_WH = WAREHOUSE.WH_KEY
  AND TRANSTKD.TRD_TO_WL = WL.WLKEY
  AND TRANSTKD.TRD_SKU = @skuKey
  AND (@locationCode IS NULL OR WL.WLCODE = @locationCode)
ORDER BY DOCINFO.DI_DATE DESC, DOCINFO.DI_REF DESC;
